export const GET_PRODUCT_LIST_REQUEST = 'GET_PRODUCT_LIST_REQUEST';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';

export const GET_PRODUCT_REVIEWS = 'GET_PRODUCT_REVIEWS'

export const GET_LISTING_SEO_DATA = 'GET_LISTING_SEO_DATA';

export const GET_FOOTER_SEO_DATA = 'GET_FOOTER_SEO_DATA'
