// export const productList = [
//   {
//     "category_id": 2,
//     "name": "Lighting usb cable (for apple)",
//     "ratings": 3,
//     "pictures": "[\"https://www.autoformindia.com/image/cache/catalog/Charger%20Cables/lightening-cable-1000x1000.jpg\", \"https://www.autoformindia.com/image/cache/catalog/product/Accessories/I%20Phone%20Usb%20Charger%20Braided-1000x1000.jpg\"]",
//     "videos": "[]",
//     "original_price": 550,
//     "discounted_price": 499,
//     // // "material": "[1]",
//     "detail": "string",
//     "description": "string",
//     "vehicle_type_id": 2,
//     // // "major_color": "[1]",
//     // // "minor_color": "[1]",
//     "brand_id": 1,
//     "product_code": "string",
//     "availability": "string",
//     "viewed": 12963,
//     // "colors": "[1]",
//     "quantity": 20,
//     "reviews": "[]",
//     "tags": "[]",
//     "suggestions": "[8]",
//     "sections": "{\"latest\": true, \"trending\": true}",
//     "additional_info": "rr33",
// "variants": [{
//   design_id: 1,
//   material_id: 1,
//   major_color_id: 1,
//   minor_color_ids: [1, 3, 4]
// }, {
//   design_id: 2,
//   material_id: 2,
//   major_color_id: 3,
//   minor_color_ids: [11, 12, 13]
// }],
//     "createdAt": "2022-06-05 13:59:08",
//     "updatedAt": "2022-06-13 18:32:23"
//   },
// ];

export const productList = [
  {
    "category_id": 2,
    "name": "Lighting usb cable (for apple)",
    "ratings": 3,
    "pictures": "[\"https://www.autoformindia.com/image/cache/catalog/Charger%20Cables/lightening-cable-1000x1000.jpg\", \"https://www.autoformindia.com/image/cache/catalog/product/Accessories/I%20Phone%20Usb%20Charger%20Braided-1000x1000.jpg\"]",
    "videos": "[]",
    "original_price": 550,
    "discounted_price": 499,
    // "material": "[1]",
    "detail": "string",
    "description": "string",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "string",
    "availability": "string",
    "viewed": 12963,
    // // "colors": "[1]",
    "quantity": 20,
    "reviews": "[]",
    "tags": "[]",
    "suggestions": "[8]",
    "sections": "{\"latest\": true, \"trending\": true}",
    "additional_info": "rr33",
    "createdAt": "2022-06-05 13:59:08",
    "updatedAt": "2022-06-13 18:32:23",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Art leather steering cover",
    "ratings": 5,
    "pictures": "[\"https://www.autoformindia.com/image/cache/catalog/product/Accessories/Steering%20Cover/ART%20LEATHER-270x270.jpg\"]",
    "videos": "[]",
    "original_price": 900,
    "discounted_price": 799,
    // "material": "[1]",
    "detail": "feefef",
    "description": "efeef",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "eewefe",
    "availability": "Yes",
    "viewed": 15127,
    // // "colors": "[1]",
    "quantity": 20,
    "reviews": "[]",
    "tags": "[]",
    "suggestions": "[8]",
    "sections": "{\"latest\": false, \"trending\": true}",
    "additional_info": "r3r3r3",
    "createdAt": "2022-06-05 14:20:45",
    "updatedAt": "2022-06-13 18:31:31",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Back seat organiser quilted (new)",
    "ratings": 5,
    "pictures": "[\"https://www.autoformindia.com/image/cache/catalog/Organizer/OR%20G1-270x270.JPG\", \"https://www.autoformindia.com/image/cache/catalog/Organizer/OR%20G1-270x270.JPG\", \"https://www.autoformindia.com/image/cache/catalog/Organizer/OR%20F1-270x270.JPG\", \"https://www.autoformindia.com/image/cache/catalog/Organizer/OR%20I%201-270x270.JPG\", \"https://www.autoformindia.com/image/cache/catalog/Organizer/OR%20H1-270x270.JPG\"]",
    "videos": "[]",
    "original_price": 1500,
    "discounted_price": 1349,
    // "material": "[1]",
    "detail": "feefef",
    "description": "efeef",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "eewefe",
    "availability": "efefe",
    "viewed": 15127,
    // "colors": "[1]",
    "quantity": 20,
    "reviews": "[]",
    "tags": "[]",
    "suggestions": "[]",
    "sections": "[]",
    "additional_info": "",
    "createdAt": "2022-06-05 14:23:13",
    "updatedAt": "2022-06-05 14:23:13",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Scooter seat cover - u active",
    "ratings": 5,
    "pictures": "[\"https://www.autoformindia.com/image/cache/catalog/bike%20seat%20covers/uni/Activa%20(4)+-270x270.jpg\", \"https://www.autoformindia.com/image/cache/catalog/bike%20seat%20covers/Active%20Full%20(1)-270x270.jpg\", \"https://www.autoformindia.com/image/cache/catalog/bike%20seat%20covers/Active%20Material%20(3)-270x270.jpg\", \"https://www.autoformindia.com/image/cache/catalog/bike%20seat%20covers/Active+%20Full%20(3)-270x270.jpg\", \"https://www.autoformindia.com/image/cache/catalog/bike%20seat%20covers/Active+%20%20(1)-270x270.jpg\"]",
    "videos": "[]",
    "original_price": 580,
    "discounted_price": 449,
    // "material": "[1]",
    "detail": "feefef",
    "description": "efeef",
    "vehicle_type_id": 1,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "eewefe",
    "availability": "efefe",
    "viewed": 15127,
    // "colors": "[1]",
    "quantity": 50,
    "reviews": "[]",
    "tags": "[]",
    "suggestions": "[]",
    "sections": "[]",
    "additional_info": "",
    "createdAt": "2022-06-05 18:24:56",
    "updatedAt": "2022-06-05 18:24:56",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Bike seat cover - u impress for royal enfield classic",
    "ratings": 4,
    "pictures": "[\"https://www.autoformindia.com/image/cache/catalog/bike%20seat%20covers/uni/Bullet%20(8)-270x270.jpg\", \"https://www.autoformindia.com/image/cache/catalog/bike%20seat%20covers/UImpress-Bullet%20Full-270x270.jpg\"]",
    "videos": "[]",
    "original_price": 525,
    "discounted_price": 499,
    // "material": "[1]",
    "detail": "feefef",
    "description": "efeef",
    "vehicle_type_id": 1,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "eewefe",
    "availability": "Yes",
    "viewed": 1512,
    // "colors": "[1]",
    "quantity": 100,
    "reviews": "[]",
    "tags": "[]",
    "suggestions": "[8]",
    "sections": "{\"latest\": false, \"trending\": true}",
    "additional_info": "3r",
    "createdAt": "2022-06-05 18:30:56",
    "updatedAt": "2022-06-13 18:30:41",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 4,
    "name": "Scooter seat cover - u active plus2",
    "ratings": 4,
    "pictures": "[\"https://www.autoformindia.com/image/cache/catalog/bike%20seat%20covers/uni/Activa%20(1)-270x270.jpg\"]",
    "videos": "[]",
    "original_price": 665,
    "discounted_price": 599,
    // "material": "[1]",
    "detail": "feefef jhjhuhdb jidsjbui  jhidf",
    "description": "<p>efeef jkkhjnbjkkj dkjnfkdfio jkhdfijhisdhf kjjhdkjf</p><p>test</p>",
    "vehicle_type_id": 1,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "eewefejdndskjnfknknk",
    "availability": "Yes",
    "viewed": 1512,
    // "colors": "[1]",
    "quantity": 100,
    "reviews": "[]",
    "tags": "[\"Black Covers\", \"Accesories\"]",
    "suggestions": "[5]",
    "sections": "{\"latest\": false, \"trending\": true}",
    "additional_info": "<p>rr33dnnnh njkdcnjksskjndkn</p><p>test</p>",
    "createdAt": "2022-06-05 18:36:36",
    "updatedAt": "2022-07-09 13:10:56",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Aux cable - 2 meter",
    "ratings": 4,
    "pictures": "[\"https://www.autoformindia.com/image/cache/catalog/Car%20Charger/Aux-Cables-New-270x270.jpg\"]",
    "videos": "[]",
    "original_price": 380,
    "discounted_price": 299,
    // "material": "[1]",
    "detail": "feefef",
    "description": "efeef",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "eewefe",
    "availability": "Yes",
    "viewed": 1512,
    // "colors": "[1]",
    "quantity": 100,
    "reviews": "[]",
    "tags": "[]",
    "suggestions": "[8]",
    "sections": "{\"latest\": false, \"trending\": true}",
    "additional_info": "ee",
    "createdAt": "2022-06-05 18:48:06",
    "updatedAt": "2022-06-13 18:24:37",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Car perfume",
    "ratings": 3.9,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/car.jpeg\"]",
    "videos": "[]",
    "original_price": 500,
    "discounted_price": 449,
    // "material": "[1]",
    "detail": "Lorem ipsum textLorem ipsum text",
    "description": "Lorem ipsum text Lorem ipsum textLorem ipsum 111",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "qwew121",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[1]",
    "quantity": 10,
    "reviews": "[]",
    "tags": "[\"Accesories\", \"Cars\"]",
    "suggestions": "[6]",
    "sections": "{\"latest\": false, \"trending\": true}",
    "additional_info": "Lorem ipsum textLorem ipsum textLorem ipsu1",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-08 17:15:55",
    "updatedAt": "2022-06-09 07:54:19",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Car Steering",
    "ratings": 2.9,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/carsteering.jpeg\"]",
    "videos": "[]",
    "original_price": 790,
    "discounted_price": 600,
    // "material": "[1]",
    "detail": "Lorem ipsum tesxt",
    "description": "Lorem ipsum tesxt Lorem ipsum tesxt Lorem ipsum tesxt",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "2334443",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[1]",
    "quantity": 20,
    "reviews": "[]",
    "tags": "[\"Leather Cover\", \"Cars\", \"Accesories\"]",
    "suggestions": "[6]",
    "sections": "{\"latest\": true, \"trending\": true}",
    "additional_info": "Lorem ipsum tesxtLorem ipsum tesxtLorem ipsum tesxtLorem ipsum tesxtLorem ipsum tesxtLorem ipsum tesxt",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-09 06:38:18",
    "updatedAt": "2022-06-09 07:53:50",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Car Mobile Holder ",
    "ratings": 4.5,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/mobileholder.jpg\"]",
    "videos": "[]",
    "original_price": 700,
    "discounted_price": 650,
    // "material": "[1]",
    "detail": "Lorem Ipsum text Lorem Ipsum text Lorem Ipsum text ",
    "description": "Lorem Ipsum text Lorem Ipsum text Lorem Ipsum text ",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "34ewdss",
    "availability": "No",
    "viewed": 10,
    // "colors": "[1]",
    "quantity": 14,
    "reviews": "[]",
    "tags": "[\"Cars\"]",
    "suggestions": "[6, 5, 3]",
    "sections": "{\"latest\": false, \"trending\": true}",
    "additional_info": "Lorem Ipsum text Lorem Ipsum text Lorem Ipsum text Lorem Ipsum text ",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-09 08:11:41",
    "updatedAt": "2022-06-09 17:11:14",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Batman dashboard miniature 1",
    "ratings": 4.5,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/batmandash.jpeg\"]",
    "videos": "[]",
    "original_price": 800,
    "discounted_price": 600,
    // "material": "[1]",
    "detail": "lorem ipsum textlorem ipsum textlorem ipsum textlorem ipsum text",
    "description": "lorem ipsum text lorem ipsum text lorem ipsum text lorem ipsum text lorem ipsum text",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "sdadasdwe",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[1]",
    "quantity": 14,
    "reviews": "[]",
    "tags": "[\"Cars\", \"Accesories\", \"Black Covers\"]",
    "suggestions": "[5]",
    "sections": "{\"latest\": true, \"trending\": false}",
    "additional_info": "lorem ipsum textlorem ipsum textlorem ipsum textlorem ipsum textlorem ipsum text",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-09 08:36:21",
    "updatedAt": "2022-06-09 16:33:30",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Dashboard miniature",
    "ratings": 5,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/batmandash.jpeg\"]",
    "videos": "[]",
    "original_price": 1000,
    "discounted_price": 800,
    // "material": "[1]",
    "detail": "lorem ipsum textlorem ipsum textlorem ipsum text",
    "description": "lorem ipsum text lorem ipsum textlorem ipsum textlorem ipsum textlorem ipsum text",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "4e34e",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[1]",
    "quantity": 1,
    "reviews": "[]",
    "tags": "[\"Black Covers\", \"Leather Cover\", \"Accesories\"]",
    "suggestions": "[5, 8]",
    "sections": "{\"latest\": false, \"trending\": true}",
    "additional_info": "loerm ipsum text loerm ipsum textloerm ipsum text",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-13 08:05:16",
    "updatedAt": "2022-06-13 08:05:49",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 1,
    "name": "CarSeat",
    "ratings": 5,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/1.png\"]",
    "videos": "[]",
    "original_price": 2339,
    "discounted_price": 1000,
    // "material": "[1]",
    "detail": "Test",
    "description": "This is a test",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "123456",
    "availability": "No",
    "viewed": 10,
    // "colors": "[1]",
    "quantity": 2,
    "reviews": "[]",
    "tags": "[\"Black Covers\", \"Leather Cover\"]",
    "suggestions": "[8]",
    "sections": "{\"latest\": false, \"trending\": true}",
    "additional_info": "test",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-13 13:14:58",
    "updatedAt": "2022-06-13 17:42:56",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "test",
    "ratings": 4,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/Screenshot 2022-06-13 at 10.32.21 PM.png\"]",
    "videos": "[]",
    "original_price": 1000,
    "discounted_price": 894,
    // "material": "[1]",
    "detail": "wewe2e2",
    "description": "wee2e",
    "vehicle_type_id": 1,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "34343",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[{\"id\": 4, \"name\": \"Red\", \"image\": \"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Colour_red.jpg/1200px-Colour_red.jpg\", \"createdAt\": \"2022-07-09T14:23:14.000Z\", \"updatedAt\": \"2022-07-09T14:23:14.000Z\"}, {\"id\": 5, \"name\": \"Black\", \"image\": \"https://upload.wikimedia.org/wikipedia/commons/5/50/Black_colour.jpg\", \"createdAt\": \"2022-07-09T14:50:47.000Z\", \"updatedAt\": \"2022-07-09T14:50:47.000Z\"}, 3, 2]",
    "quantity": 10,
    "reviews": "[]",
    "tags": "[]",
    "suggestions": "[4]",
    "sections": "{\"latest\": true, \"trending\": true}",
    "additional_info": "e2e2e2",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-13 17:49:32",
    "updatedAt": "2022-07-31 15:59:58",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "Demo",
    "ratings": 5,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/445543.jpg\"]",
    "videos": "[\"https://balonkun.s3.amazonaws.com/products/445543.jpg\"]",
    "original_price": 900,
    "discounted_price": 700,
    // "material": "[1]",
    "detail": "Testing",
    "description": "<p>Test Test, Test &nbsp;check</p>",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "Deweasa",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[1]",
    "quantity": 33,
    "reviews": "[]",
    "tags": "[\"Cars\", \"Leather Cover\", \"Black Covers\", \"Accesories\"]",
    "suggestions": "[8]",
    "sections": "{\"latest\": true, \"trending\": false}",
    "additional_info": "lorem ipsum",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-14 05:49:21",
    "updatedAt": "2022-07-08 15:20:30",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 1,
    "name": "testing Trending product 1",
    "ratings": 3.4,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/d3 (3)-1000x1000 (1).jpg\", \"https://balonkun.s3.amazonaws.com/products/d3 (1)-1000x1000.jpg\"]",
    "videos": "[]",
    "original_price": 1003,
    "discounted_price": 899,
    // "material": "[1]",
    "detail": "Seat Cover D3- Test",
    "description": "<h2><strong>Varius tempor</strong></h2><p>Aliquam dis vulputate vulputate integer sagittis. Faucibus dolor ornare faucibus vel sed et eleifend habitasse amet. Montes, mauris varius ac est bibendum. Scelerisque a, risus ac ante. Velit consectetur neque, elit, aliquet. Non varius proin sed urna, egestas consequat laoreet diam tincidunt. Magna eget faucibus cras justo, tortor sed donec tempus. Imperdiet consequat, quis diam arcu, nulla lobortis justo netus dis. Eu in fringilla vulputate nunc nec. Dui, massa viverr .</p><p><strong>More details&nbsp;</strong></p><ul><li>Aliquam dis vulputate vulputate integer sagittis. Faucibus ds diam arcu, nulla lobortis justo netus dis. Eu in fringilla vulputate nunc nec. Dui, massa viverr.<br>Aliquam dis vulputate vulputate integer sagittis. Faucibus ds diam arcu, nulla lobortis justo netus dis. Eu in fringilla vulputate nunc nec. Dui, massa viverr.<br>Aliquam dis vulputate vulputate integer sagittis. Faucibus ds diam arcu, nulla lobortis justo netus dis. Eu in fringilla vulputate nunc nec. Dui, massa viverr.<br>Aliquam dis vulputate vulputate integer sagittis. Faucibus ds diam arcu, nulla lobortis justo netus dis. Eu in fringilla vulputate nunc nec. Dui, massa viverr.</li></ul>",
    "vehicle_type_id": 2,
    // "major_color": "[1]",
    // "minor_color": "[1]",
    "brand_id": 1,
    "product_code": "code",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[5, 4, 3, 2]",
    "quantity": 7,
    "reviews": "[]",
    "tags": "[]",
    "suggestions": "[8]",
    "sections": "{\"latest\": true, \"trending\": true}",
    "additional_info": "<p>Aliquam dis vulputate vulputate integer sagittis. Faucibus dolor ornare faucibus vel sed et eleifend habitasse amet. Montes, mauris varius ac est bibendum. Scelerisque a, risus ac ante. Velit consectetur neque, elit, aliquet. Non varius proin sed urna.</p><p>&nbsp;</p><p>Aliquam dis vulputate vulputate integer sagittis. Faucibus dolor ornare faucibus vel sed et eleifend habitasse amet. Montes, mauris varius ac est bibendum. Scelerisque a, risus ac ante. Velit consectetur neque, elit, aliquet. Non varius proin sed urna.workin</p>",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-06-14 17:10:24",
    "updatedAt": "2022-07-23 05:04:28",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 4,
    "name": "BIKE SEAT COVER - U IMPRESS-Test",
    "ratings": 5,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/U Impress02-1000x1000.jpg\"]",
    "videos": "[]",
    "original_price": 111,
    "discounted_price": 222,
    // "material": "[1]",
    "detail": "BIKE SEAT COVER - U IMPRESS-test",
    "description": "BIKE SEAT COVER - U IMPRESS-test",
    "vehicle_type_id": 1,
    // "major_color": "[5]",
    // "minor_color": "[5]",
    "brand_id": 1,
    "product_code": "1122",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[5]",
    "quantity": 3,
    "reviews": "[]",
    "tags": "[\"Black Covers\", \"Accesories\"]",
    "suggestions": "[4]",
    "sections": "{\"latest\": true, \"trending\": true}",
    "additional_info": "BIKE SEAT COVER - U IMPRESS-test",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-07-23 05:00:59",
    "updatedAt": "2022-07-23 05:00:59",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  },
  {
    "category_id": 2,
    "name": "BACK SUPPORT | LUMBAR SUPPORT (L1)",
    "ratings": 5,
    "pictures": "[\"https://balonkun.s3.amazonaws.com/products/L1 C1-1000x1000.jpg\"]",
    "videos": "[]",
    "original_price": 111,
    "discounted_price": 222,
    // "material": "[1]",
    "detail": "BACK SUPPORT | LUMBAR SUPPORT (L1)- Test",
    "description": "BACK SUPPORT | LUMBAR SUPPORT (L1)- Test",
    "vehicle_type_id": 2,
    // "major_color": "[5]",
    // "minor_color": "[5]",
    "brand_id": 1,
    "product_code": "1133",
    "availability": "Yes",
    "viewed": 10,
    // "colors": "[5, 4]",
    "quantity": 4,
    "reviews": "[]",
    "tags": "[\"Accesories\"]",
    "suggestions": "[4]",
    "sections": "{\"latest\": true, \"trending\": true}",
    "additional_info": "BACK SUPPORT | LUMBAR SUPPORT (L1)- Test",
    "isLatest": 0,
    "isTrending": 0,
    "createdAt": "2022-07-23 05:02:34",
    "updatedAt": "2022-07-31 06:46:17",
    "variants": [{
      design_id: 1,
      material_id: 1,
      major_color_id: 1,
      minor_color_ids: [1, 3, 4]
    }, {
      design_id: 2,
      material_id: 2,
      major_color_id: 3,
      minor_color_ids: [11, 12, 13]
    }],
  }
];
