import "dotenv/config.js";

const {
    ENV,
    DATABASE_DIALECT,
    PORT,
    API_DOCUMENTATION_URL,
    API_BASE_URL,
    AUTHENTICATOR_SWITCH,
    API_VALIDATOR_SWITCH,
    JWT_TOKEN_SECRET_KEY,
    LOGIN_TOKEN_EXPIRY,
    VERIFY_EMAIL_TOKEN_EXPIRY,
    FORGOT_PASSWORD_TOKEN_EXPIRY,
    API_KEY,
    RESET_DATBASE_SWITCH,

    DEV_DATABASE_HOST,
    DEV_DATABASE_USER,
    DEV_DATABASE_PASSWORD,
    DEV_DATABASE_NAME,
    DEV_DATABASE_PORT,


    PROD_DATABASE_HOST,
    PROD_DATABASE_USER,
    PROD_DATABASE_PASSWORD,
    PROD_DATABASE_NAME,
    PROD_DATABASE_PORT,
    PROD_API_URL,
    PROD_WEB_URL,
    PROD_ADMIN_URL,
    PROD_WEB_URL_1,
    PROD_WEB_URL_2,

    DEV_API_URL,
    DEV_WEB_URL,
    DEV_ADMIN_URL,
    DEV_WEB_URL_1,
    DEV_WEB_URL_2,

    LOCAL_DATABASE_HOST,
    LOCAL_DATABASE_USER,
    LOCAL_DATABASE_PASSWORD,
    LOCAL_DATABASE_NAME,
    LOCAL_DATABASE_PORT,
    LOCAL_API_URL,
    LOCAL_WEB_URL,
    LOCAL_ADMIN_URL,

    SMTP_SERVICE,
    SMTP_EMAIL,
    SMTP_PASSWORD,
    SMTP_SENDER_EMAIL,

    ADMIN_EMAIL
} = process.env;

let db_config;
if (ENV === "PROD") {
    db_config = {
        DATABASE_HOST: PROD_DATABASE_HOST,
        DATABASE_USER: PROD_DATABASE_USER,
        DATABASE_PASSWORD: PROD_DATABASE_PASSWORD,
        DATABASE_NAME: PROD_DATABASE_NAME,
        DATABASE_PORT: PROD_DATABASE_PORT,
        API_URL: PROD_API_URL,
        WEB_URL: PROD_WEB_URL_1,
        ADMIN_URL: PROD_ADMIN_URL,}
} else if (ENV === "DEV") {
    db_config = {
        DATABASE_HOST: DEV_DATABASE_HOST,
        DATABASE_USER: DEV_DATABASE_USER,
        DATABASE_PASSWORD: DEV_DATABASE_PASSWORD,
        DATABASE_NAME: DEV_DATABASE_NAME,
        DATABASE_PORT: DEV_DATABASE_PORT,
        API_URL: DEV_API_URL,
        WEB_URL: DEV_WEB_URL,
        ADMIN_URL: DEV_ADMIN_URL,
    }
} else {
    db_config = {
        DATABASE_HOST: LOCAL_DATABASE_HOST,
        DATABASE_USER: LOCAL_DATABASE_USER,
        DATABASE_PASSWORD: LOCAL_DATABASE_PASSWORD,
        DATABASE_NAME: LOCAL_DATABASE_NAME,
        DATABASE_PORT: LOCAL_DATABASE_PORT,
        API_URL: LOCAL_API_URL,
        WEB_URL: LOCAL_WEB_URL,
        ADMIN_URL: LOCAL_ADMIN_URL,
    }
}
export default {
    ENV,
    API_DOCUMENTATION_URL,
    DATABASE_DIALECT,
    PORT,
    ALLOWED_ORIGINS: [LOCAL_WEB_URL, DEV_WEB_URL, DEV_ADMIN_URL, LOCAL_ADMIN_URL, DEV_WEB_URL_1, DEV_WEB_URL_2,
        PROD_WEB_URL, PROD_WEB_URL_1, PROD_WEB_URL_2, PROD_ADMIN_URL, "https://autoformindia.com", "https://www.autoformindia.com", "http://localhost:5086", "http://localhost:4000"],
    API_BASE_URL,
    AUTHENTICATOR_SWITCH,
    API_VALIDATOR_SWITCH,
    JWT_TOKEN_SECRET_KEY,
    LOGIN_TOKEN_EXPIRY,
    FORGOT_PASSWORD_TOKEN_EXPIRY,
    API_KEY,
    RESET_DATBASE_SWITCH,
    SMTP_SERVICE,
    SMTP_EMAIL,
    SMTP_PASSWORD,
    SMTP_SENDER_EMAIL,
    VERIFY_EMAIL_TOKEN_EXPIRY,
    ADMIN_EMAIL,
    ...db_config,
}
;
