import React from "react";
import { Helmet } from "react-helmet";

const TermsAndConditions = () => {
  return (
    <div className="tncWrapper">

      <Helmet>
        <title>TERMS AND CONDITIONS OF USE AGREEMENT</title>
        <meta name='description' content="Discover Autoform India's terms and conditions of use agreement. Stay informed and compliant with our website's guidelines for a seamless user experience." />
      </Helmet>

      <div className='tncInternal'>
        <h1>TERMS AND CONDITIONS OF USE AGREEMENT</h1>
        <br />
        <p>
          <i>This Agreement is in accordance with the Information Technology Act, 2000.This document is
          generated by a computer system and forms “Electronic Record” as per the provisions of the
          Information Technology Act, 2000.</i>
        </p>

        <p><i>This Agreement is issued on this website in compliance with the Rule 3(1) of the Information
          Technology (Intermediaries Guidelines) Rules, 2011.The rule states that for the usage/access of the
          autoformindia.com the rules and regulations, privacy policy and user agreement should be
          published on the website</i>
        </p>

        <p>Please read this terms and conditions of use agreement carefully. By using this website (autoformindia.com) or the services provided through this website you, i.e. Guest or registered user or purchaser (“user”), agree to be bound by all of the terms and conditions of this agreement, which also includes the amendments made in such terms and conditions from time to time.</p>
        
        <p>
          Disclaimer: Please note that the information presented on this website is for general information purpose only. Autoform India makes endeavours to keep all the details or information correct and up to date but in no way makes any representations or warranty of any kind, express or implied, about the suitability or availability of any product represented on this website or through the information, pictures or related graphics contained on this website for any purpose whatsoever. Autoform India further clarifies that the pictorial representations of the products are for information and marketing purposes only and nor orders or transactions for sale or purchase of such products are accepted through this website or any portal associated with this website.
        </p>

        <p>Should you have any further queries, please contact us at:</p>
        <p>Email ID:marketing@autoformindia.com</p>
        <p>Phone Number:092784 11411</p>
        <div className='empty'></div>
      </div>

      <div className="tncInternal">
        <h3>Website Interface</h3>
        <p>The domain is autoformindia.com which is managed and operated by “ThreeZeroInc”. The terms “We” “Us” “Our” shall denote “ThreeZeroInc”. We provide autoformindia.com, all information which includes information available to the user (hereinafter referred to as “You”) in accordance with the terms and condition applicable.</p>
        <p>Any access, browsing or in other respect using the website shall mean that you have agreed to the entire terms and conditions of use applicable to you.</p>
        <p>When you visit or purchase any product from our website it will mean that you are engaged in our “Service” and in turn you are bound by this “Terms and Conditions of Use Agreement” (hereinafter referred to as “terms”).These terms are applicable on all users including browsers, vendors, customers, merchants, and/ or contributors of content.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Terms of Offer</h3>
        <p>This Website offers for sale certain products. By placing an order for such products through this website, you agree to the terms set forth in this Agreement.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Customer Soliciation</h3>
        <p>Unless you notify our third-party call center representatives or direct Autoform sales representative, while they are calling you, of your desire to opt out from further direct company communications and solicitations, you are agreeing to continue to receive further emails and call solicitations from Autoform and its designated in house or third-party call team(s).</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Proprietary Rights</h3>
        <br />
        <p>Autoform has proprietary rights and trade secrets on this website. You may not copy, reproduce, resell or redistribute anything distributed on or through this website. Autoform also has rights to all trademarks, trade dresses and specific layouts of this webpage, including calls to action, text placement, images and other information.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Use Of Website By Eligible Person</h3>
        <br />
        <p>This website can be used by the person who is eligible to form legally binding contract in accordance with the Indian Contract Act, 1872. A minor, a person of unsound mind and a person who is barred by the law, should not use or make any transaction from this site. However, if a minor wants to use this website or make any transaction from this website then in that case same is to done through the legal guardian of the minor. The legal guardian will be bound by any act done by the minor.</p>
        <div className="empty"></div>
      </div>
      
      <div className="tncInternal">
        <h3>User Accounts, its Conduct & Control</h3>
        <br />
        <p>To purchase any product from our website you need to get yourself registered by creating a “User Account”. Once you have completed the registration process, a User ID and a Password is generated. Thereafter, you can use this website only after logging in to the account. The information provided by the user should be correct, true and adequate. If the information provided is not so, then the website holds the right to cancel the said account. The responsibility to maintain the confidentiality of the account is solely of the user. The user will be solely liable for the misuse of the account. The user agrees to inform Autoform, if there is any unauthorised use of the account, and that he/she will log out of the account after the use of the same.</p>
        <p>If the user fails to comply with above mentioned terms and condition, then in that case, the Autoform cannot be made liable for the loss or damages arising from the same.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Privacy</h3>
        <br />
        <p>Autoform believes strongly in protecting user privacy. Please refer to its privacy policy, incorporated by reference herein that is posted on this website.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Feedbacks, Comments and other Submissions</h3>
        <br />
        <p>Any feedback, comments or any other submission made by the user should not be unlawful, abusive or obscene. They should not be used in such a way that they harm the right of another person which includes other users. The words used by the user should not be such that they harass any person. Autoform will not take any responsibility of any liability which user may suffer as consequences of such feedback, comments or any other submission. By the way of such feedback, comments or any other submission the user should not display, upload or publish what infringes the intellectual property rights of any person.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Billing Information</h3>
        <br />
        <p>The purchaser of the product should not use the product for the commercial purpose or for re-sale. If the user contravenes the same, then we reserve a right to cancel such orders.</p>
        <p>The user should provide true and correct billing address. In case the user provides untrue or incorrect billing address then we will not be liable for any loss or damage as a consequence of the same.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Goods And Services Tax</h3>
        <br />
        <p>If you purchase any product, you will be responsible for paying any applicable GST.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Prohibition Imposed on User</h3>
        <br />
        <p><b>The user is prohibited from using the website:</b></p>
        <ul>
          <li>for unlawful purpose; or</li>
          <li>for commercial use or for resale; or</li>
          <li>in violation of any law for the time being in force; or</li>
          <li>in such a way that it infringes any intellectual property rights of any other person</li>
          <li>in such a way that the website is affected by the computer virus or malware.</li>
        </ul>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Metaspace Conditions</h3>
        <br />
        <p><b>The user should not use the product for any illegal or unlawful purpose.</b></p>
        <ul>
          <li>We don’t guarantee any accuracy and reliability for the content or colour display on this website.</li>
          <li>We ensure that the products sold by us are of good quality. If in case it is not up to the expectation of the user, then it will be governed by the warranty on that product.</li>
          <li>We reserve the right to modify the price and terms of service.</li>
          <li>We reserve the right to change the price of the product any time.</li>
          <li>We reserve the right to limit the number of product that a user can purchase.</li>
          <li>We can discontinue the service of a user anytime, if it contravenes any terms and condition.</li>
          <li>We will not be liable for any loss or damage which the user suffers because of the changes in
            the price of the product.</li>
        </ul>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Limitations of Liability</h3>
        <br />
        <p>Autoform will not be liable for any direct, indirect, incidental, special or consequential damages in connection with these terms or products sold on this website, in any manner, including liabilities resulting from:</p>
        <ul>
          <li>the use or the inability to use this website’s content or services;</li>
          <li>the cost of procuring substitute services or content;</li>
          <li>any products purchased or obtained or transactions entered into through this website; or</li>
          <li>any lost profits you allege.</li>
        </ul>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Third Party Links or Sites</h3>
        <br />
        <p>When the users access the domain of Autoform, they also use the services of third party, in such cases the user will be governed by the policies of the third party. We will not be liable for any loss or damages in connection to the third party’s website.</p>
        <p>We also use the service of the third parties for advertisement. It does not signify that these third parties are affiliated with Autoform or they act on behalf of Autoform. The user should examine such information before relying on it as provided by the third party.</p>
        <p>We will not be liable for loss or damages incurred by the user if he relied on the wrong information provided by the third party.</p>
        <p>The company Autoform India is the owner of the autoformindia.com.Any rights pertaining to Intellectual Property are reserved by Autoform. Further, the content displayed on this website is owned by Autoform.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Cancellation/Refund Policy</h3>
        <br />
        <p>Autoform believes in providing an easy and convenient service to you. Please refer to its cancellation policy, incorporated by reference herein that is posted on this website.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Termination/Access Restriction</h3>
        <br />
        <p>Autoform hereby declares its right to terminate your access to this website or restrict the use of it, in a limited manner, at its sole discretion, at any time without giving any advance notice.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Changes to Terms</h3>
        <br />
        <p>Autoform reserves the right, in its sole discretions, to change these terms. The most current version of the terms will take effect over all the previous versions. Autoform encourages you to periodically review the terms to stay informed of our updates.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Jurisdiction/Sale Only In India</h3>
        <br />
        <p>The product/material displayed on this website is only meant to be sold in India. Autoform does not represent that it is to be sold outside the territory of India. If anyone places any order from outside India, then Autoform is not responsible to supply it outside India. Users, who gain access of this website from a territory outside India, do so at their own risk, and they must bear all responsibility for compliance with any applicable local laws.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Law Governing the Disputes</h3>
        <br />
        <p>This Website originates from Noida, Uttar Pradesh, India. These terms will be governed by the laws of India and laws of Uttar Pradesh in particular. Neither you nor Autoform will commence or prosecute any suit, proceeding or claim to enforce the provisions of these terms, to recover damages for breach of or default of these terms, or otherwise arising under or by reason of these terms, other than in courts located in Noida, Uttar Pradesh. By using this website or making purchase, you consent to the jurisdiction and venue of such courts in connection with any action, suit, proceeding or claim arising under or by reason of these terms. Use of this website is unauthorized in any jurisdiction that does not give effect to all provisions of these terms, in their entirety.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Force Majeure</h3>
        <br />
        <p>Autoform will not be deemed in default hereunder or held responsible for any cessation, interruption or delay in the performance of its obligations hereunder due to earthquake, flood, fire, storm, natural disaster, act of God, war, terrorism, armed conflict, labor strike, lockout, or boycott.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Cessation of Operation</h3>
        <br />
        <p>Autoform may at any time, in its sole discretion and without advance notice to you, cease operation of this website and distribution of the Services.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal">
        <h3>Assignment</h3>
        <br />
        <p>You may not assign your rights and obligations under these terms to anyone. Autoform may assign its rights and obligations under these terms in its sole discretion and without advance notice to you.</p>
        <div className="empty"></div>
      </div>

      <div className="tncInternal-last">
        <h3>Disclaimer to Third Party Rights</h3>
        <br />
        <p>autoformindia.com is a proprietary web portal of the company ‘Autoform India’ that operates as an independent manufacturer & merchant of customised automobile accessories and merchandise compatible with various automobile brands. The display of trade names, designs, make, model, sub-model, variants, marque, shapes or images of any automobile or brand on its website or any affiliated webpage thereof, shall in no way imply any association or affiliation with or endorsement from the respective automobiles and / or brands and the purpose of such display shall only be to facilitate marketing and sale of such customised automobile accessories and merchandise to the visitors.</p>
        <p>The rights to intellectual property contained in such display shall belong to their respective owners with no claim whatsoever of Autoform India.</p>
        <p>In addition, the proprietary products of Autoform India marketed and sold on this website are independently designed and manufactured without being influenced, endorsed or sponsored by any automobile manufacturer or brand.”</p>
        <p>By using this website or making purchases from this website you agree to be bound by all of the terms and conditions of this agreement.</p>
      </div>
    </div>
  );
};

export default TermsAndConditions;
