import React from "react";
import { Helmet } from "react-helmet";

const TermsAndConditions = () => {
  return (
    <div className="static-page-container">
      <Helmet>
        <title>TERMS AND CONDITIONS OF USE AGREEMENT</title>
        <meta name='description' content="Discover Autoform India's terms and conditions of use agreement. Stay informed and compliant with our website's guidelines for a seamless user experience." />
      </Helmet>

      <section className="static-hero">
        <h1>TERMS & CONDITIONS</h1>
        <p className="hero-subtitle">Use Agreement & Legal Framework</p>
      </section>

      <div className="max-w-[1200px] mx-auto px-4 md:px-0">
        <div className="static-card">
          <p>
            <i className="text-slate-500 italic block mb-4 border-l-2 border-slate-200 pl-4">
              This Agreement is in accordance with the Information Technology Act, 2000. This document is
              generated by a computer system and forms “Electronic Record” as per the provisions of the
              Information Technology Act, 2000.
            </i>
          </p>

          <p>
            <i className="text-slate-500 italic block mb-6 border-l-2 border-slate-200 pl-4">
              This Agreement is issued on this website in compliance with the Rule 3(1) of the Information
              Technology (Intermediaries Guidelines) Rules, 2011.
            </i>
          </p>

          <p>Please read this terms and conditions of use agreement carefully. By using this website (autoformindia.com) or the services provided through this website you, i.e. Guest or registered user or purchaser (“user”), agree to be bound by all of the terms and conditions of this agreement, which also includes the amendments made in such terms and conditions from time to time.</p>
          
          <p>
            <strong>Disclaimer:</strong> Please note that the information presented on this website is for general information purpose only. Autoform India makes endeavours to keep all the details or information correct and up to date but in no way makes any representations or warranty of any kind, express or implied, about the suitability or availability of any product represented on this website.
          </p>

          <div className="bg-slate-50 p-6 rounded-xl border border-slate-100 my-8">
            <p className="font-bold text-slate-900 mb-2">Should you have any further queries, please contact us at:</p>
            <p className="mb-1"><strong>Email ID:</strong> marketing@autoformindia.com</p>
            <p><strong>Phone Number:</strong> 092784 11411</p>
          </div>

          <div className="section-divider"></div>

          <h3>Website Interface</h3>
          <p>The domain is autoformindia.com which is managed and operated by “ThreeZeroInc”. The terms “We” “Us” “Our” shall denote “ThreeZeroInc”. We provide autoformindia.com, all information which includes information available to the user in accordance with the terms and condition applicable.</p>
          <p>Any access, browsing or in other respect using the website shall mean that you have agreed to the entire terms and conditions of use applicable to you.</p>

          <h3>Terms of Offer</h3>
          <p>This Website offers for sale certain products. By placing an order for such products through this website, you agree to the terms set forth in this Agreement.</p>

          <h3>Customer Solicitation</h3>
          <p>Unless you notify our third-party call center representatives or direct Autoform sales representative, while they are calling you, of your desire to opt out from further direct company communications and solicitations, you are agreeing to continue to receive further emails and call solicitations from Autoform.</p>

          <h3>Proprietary Rights</h3>
          <p>Autoform has proprietary rights and trade secrets on this website. You may not copy, reproduce, resell or redistribute anything distributed on or through this website. Autoform also has rights to all trademarks, trade dresses and specific layouts of this webpage, including calls to action, text placement, images and other information.</p>

          <h3>Use Of Website By Eligible Person</h3>
          <p>This website can be used by the person who is eligible to form legally binding contract in accordance with the Indian Contract Act, 1872. A minor, a person of unsound mind and a person who is barred by the law, should not use or make any transaction from this site.</p>
          
          <h3>User Accounts, its Conduct & Control</h3>
          <p>To purchase any product from our website you need to get yourself registered by creating a “User Account”. Once you have completed the registration process, a User ID and a Password is generated. Thereafter, you can use this website only after logging in to the account.</p>

          <h3>Feedbacks, Comments and other Submissions</h3>
          <p>Any feedback, comments or any other submission made by the user should not be unlawful, abusive or obscene. They should not be used in such a way that they harm the right of another person which includes other users.</p>

          <h3>Prohibition Imposed on User</h3>
          <p><strong>The user is prohibited from using the website:</strong></p>
          <ul>
            <li>For unlawful purpose; or</li>
            <li>For commercial use or for resale; or</li>
            <li>In violation of any law for the time being in force; or</li>
            <li>In such a way that it infringes any intellectual property rights of any other person</li>
            <li>In such a way that the website is affected by the computer virus or malware.</li>
          </ul>

          <h3>Limitations of Liability</h3>
          <p>Autoform will not be liable for any direct, indirect, incidental, special or consequential damages in connection with these terms or products sold on this website, in any manner, including liabilities resulting from:</p>
          <ul>
            <li>The use or the inability to use this website’s content or services;</li>
            <li>The cost of procuring substitute services or content;</li>
            <li>Any products purchased or obtained or transactions entered into through this website.</li>
          </ul>

          <h3>Cancellation/Refund Policy</h3>
          <p>Autoform believes in providing an easy and convenient service to you. Please refer to its cancellation policy, incorporated by reference herein that is posted on this website.</p>

          <h3>Jurisdiction/Sale Only In India</h3>
          <p>The product/material displayed on this website is only meant to be sold in India. Autoform does not represent that it is to be sold outside the territory of India.</p>

          <footer className="mt-12 pt-8 border-t border-slate-100 text-slate-400 text-sm italic">
            By using this website or making purchases from this website you agree to be bound by all of the terms and conditions of this agreement.
          </footer>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
